apiVersion: v1
kind: Service
metadata:
  name: {{ template "docker-registry.fullname" . }}-redis
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 6379
      protocol: TCP
      name: redis-port
      targetPort: 6379
  selector:
    app: {{ template "docker-registry.name" . }}-redis
    release: {{ .Release.Name }}
