apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.fullname" . }}
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.secrets.htpasswd }}
  htpasswd: {{ .Values.secrets.htpasswd  | b64enc  | quote }}
  {{- end }}
  {{- if .Values.secrets.haSharedSecret }}
  haSharedSecret: {{ .Values.secrets.haSharedSecret | b64enc | quote }}
  {{- else }}
  haSharedSecret: {{ include "haSharedSecret.password" . }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  redisPassword: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- else }}
  redisPassword: {{ include "redis.password" . }}
  {{- end }}
#  test: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}